
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Vendor` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Vendor
 * 
 */
export type VendorModel = runtime.Types.Result.DefaultSelection<Prisma.$VendorPayload>

export type AggregateVendor = {
  _count: VendorCountAggregateOutputType | null
  _avg: VendorAvgAggregateOutputType | null
  _sum: VendorSumAggregateOutputType | null
  _min: VendorMinAggregateOutputType | null
  _max: VendorMaxAggregateOutputType | null
}

export type VendorAvgAggregateOutputType = {
  id: number | null
  userId: number | null
}

export type VendorSumAggregateOutputType = {
  id: number | null
  userId: number | null
}

export type VendorMinAggregateOutputType = {
  id: number | null
  createdAt: Date | null
  userId: number | null
}

export type VendorMaxAggregateOutputType = {
  id: number | null
  createdAt: Date | null
  userId: number | null
}

export type VendorCountAggregateOutputType = {
  id: number
  createdAt: number
  userId: number
  _all: number
}


export type VendorAvgAggregateInputType = {
  id?: true
  userId?: true
}

export type VendorSumAggregateInputType = {
  id?: true
  userId?: true
}

export type VendorMinAggregateInputType = {
  id?: true
  createdAt?: true
  userId?: true
}

export type VendorMaxAggregateInputType = {
  id?: true
  createdAt?: true
  userId?: true
}

export type VendorCountAggregateInputType = {
  id?: true
  createdAt?: true
  userId?: true
  _all?: true
}

export type VendorAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Vendor to aggregate.
   */
  where?: Prisma.VendorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Vendors to fetch.
   */
  orderBy?: Prisma.VendorOrderByWithRelationInput | Prisma.VendorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.VendorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Vendors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Vendors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Vendors
  **/
  _count?: true | VendorCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: VendorAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: VendorSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: VendorMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: VendorMaxAggregateInputType
}

export type GetVendorAggregateType<T extends VendorAggregateArgs> = {
      [P in keyof T & keyof AggregateVendor]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateVendor[P]>
    : Prisma.GetScalarType<T[P], AggregateVendor[P]>
}




export type VendorGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VendorWhereInput
  orderBy?: Prisma.VendorOrderByWithAggregationInput | Prisma.VendorOrderByWithAggregationInput[]
  by: Prisma.VendorScalarFieldEnum[] | Prisma.VendorScalarFieldEnum
  having?: Prisma.VendorScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: VendorCountAggregateInputType | true
  _avg?: VendorAvgAggregateInputType
  _sum?: VendorSumAggregateInputType
  _min?: VendorMinAggregateInputType
  _max?: VendorMaxAggregateInputType
}

export type VendorGroupByOutputType = {
  id: number
  createdAt: Date
  userId: number
  _count: VendorCountAggregateOutputType | null
  _avg: VendorAvgAggregateOutputType | null
  _sum: VendorSumAggregateOutputType | null
  _min: VendorMinAggregateOutputType | null
  _max: VendorMaxAggregateOutputType | null
}

export type GetVendorGroupByPayload<T extends VendorGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<VendorGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof VendorGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], VendorGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], VendorGroupByOutputType[P]>
      }
    >
  >



export type VendorWhereInput = {
  AND?: Prisma.VendorWhereInput | Prisma.VendorWhereInput[]
  OR?: Prisma.VendorWhereInput[]
  NOT?: Prisma.VendorWhereInput | Prisma.VendorWhereInput[]
  id?: Prisma.IntFilter<"Vendor"> | number
  createdAt?: Prisma.DateTimeFilter<"Vendor"> | Date | string
  userId?: Prisma.IntFilter<"Vendor"> | number
  products?: Prisma.ProductListRelationFilter
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  store?: Prisma.XOR<Prisma.StoreNullableScalarRelationFilter, Prisma.StoreWhereInput> | null
}

export type VendorOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  products?: Prisma.ProductOrderByRelationAggregateInput
  user?: Prisma.UserOrderByWithRelationInput
  store?: Prisma.StoreOrderByWithRelationInput
}

export type VendorWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  userId?: number
  AND?: Prisma.VendorWhereInput | Prisma.VendorWhereInput[]
  OR?: Prisma.VendorWhereInput[]
  NOT?: Prisma.VendorWhereInput | Prisma.VendorWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"Vendor"> | Date | string
  products?: Prisma.ProductListRelationFilter
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  store?: Prisma.XOR<Prisma.StoreNullableScalarRelationFilter, Prisma.StoreWhereInput> | null
}, "id" | "userId">

export type VendorOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  _count?: Prisma.VendorCountOrderByAggregateInput
  _avg?: Prisma.VendorAvgOrderByAggregateInput
  _max?: Prisma.VendorMaxOrderByAggregateInput
  _min?: Prisma.VendorMinOrderByAggregateInput
  _sum?: Prisma.VendorSumOrderByAggregateInput
}

export type VendorScalarWhereWithAggregatesInput = {
  AND?: Prisma.VendorScalarWhereWithAggregatesInput | Prisma.VendorScalarWhereWithAggregatesInput[]
  OR?: Prisma.VendorScalarWhereWithAggregatesInput[]
  NOT?: Prisma.VendorScalarWhereWithAggregatesInput | Prisma.VendorScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Vendor"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Vendor"> | Date | string
  userId?: Prisma.IntWithAggregatesFilter<"Vendor"> | number
}

export type VendorCreateInput = {
  createdAt?: Date | string
  products?: Prisma.ProductCreateNestedManyWithoutVendorInput
  user: Prisma.UserCreateNestedOneWithoutVendorInput
  store?: Prisma.StoreCreateNestedOneWithoutVendorInput
}

export type VendorUncheckedCreateInput = {
  id?: number
  createdAt?: Date | string
  userId: number
  products?: Prisma.ProductUncheckedCreateNestedManyWithoutVendorInput
  store?: Prisma.StoreUncheckedCreateNestedOneWithoutVendorInput
}

export type VendorUpdateInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  products?: Prisma.ProductUpdateManyWithoutVendorNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutVendorNestedInput
  store?: Prisma.StoreUpdateOneWithoutVendorNestedInput
}

export type VendorUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  products?: Prisma.ProductUncheckedUpdateManyWithoutVendorNestedInput
  store?: Prisma.StoreUncheckedUpdateOneWithoutVendorNestedInput
}

export type VendorCreateManyInput = {
  id?: number
  createdAt?: Date | string
  userId: number
}

export type VendorUpdateManyMutationInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VendorUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type VendorNullableScalarRelationFilter = {
  is?: Prisma.VendorWhereInput | null
  isNot?: Prisma.VendorWhereInput | null
}

export type VendorCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type VendorAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type VendorMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type VendorMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type VendorSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type VendorScalarRelationFilter = {
  is?: Prisma.VendorWhereInput
  isNot?: Prisma.VendorWhereInput
}

export type VendorCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.VendorCreateWithoutUserInput, Prisma.VendorUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.VendorCreateOrConnectWithoutUserInput
  connect?: Prisma.VendorWhereUniqueInput
}

export type VendorUncheckedCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.VendorCreateWithoutUserInput, Prisma.VendorUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.VendorCreateOrConnectWithoutUserInput
  connect?: Prisma.VendorWhereUniqueInput
}

export type VendorUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.VendorCreateWithoutUserInput, Prisma.VendorUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.VendorCreateOrConnectWithoutUserInput
  upsert?: Prisma.VendorUpsertWithoutUserInput
  disconnect?: Prisma.VendorWhereInput | boolean
  delete?: Prisma.VendorWhereInput | boolean
  connect?: Prisma.VendorWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.VendorUpdateToOneWithWhereWithoutUserInput, Prisma.VendorUpdateWithoutUserInput>, Prisma.VendorUncheckedUpdateWithoutUserInput>
}

export type VendorUncheckedUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.VendorCreateWithoutUserInput, Prisma.VendorUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.VendorCreateOrConnectWithoutUserInput
  upsert?: Prisma.VendorUpsertWithoutUserInput
  disconnect?: Prisma.VendorWhereInput | boolean
  delete?: Prisma.VendorWhereInput | boolean
  connect?: Prisma.VendorWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.VendorUpdateToOneWithWhereWithoutUserInput, Prisma.VendorUpdateWithoutUserInput>, Prisma.VendorUncheckedUpdateWithoutUserInput>
}

export type VendorCreateNestedOneWithoutStoreInput = {
  create?: Prisma.XOR<Prisma.VendorCreateWithoutStoreInput, Prisma.VendorUncheckedCreateWithoutStoreInput>
  connectOrCreate?: Prisma.VendorCreateOrConnectWithoutStoreInput
  connect?: Prisma.VendorWhereUniqueInput
}

export type VendorUpdateOneRequiredWithoutStoreNestedInput = {
  create?: Prisma.XOR<Prisma.VendorCreateWithoutStoreInput, Prisma.VendorUncheckedCreateWithoutStoreInput>
  connectOrCreate?: Prisma.VendorCreateOrConnectWithoutStoreInput
  upsert?: Prisma.VendorUpsertWithoutStoreInput
  connect?: Prisma.VendorWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.VendorUpdateToOneWithWhereWithoutStoreInput, Prisma.VendorUpdateWithoutStoreInput>, Prisma.VendorUncheckedUpdateWithoutStoreInput>
}

export type VendorCreateNestedOneWithoutProductsInput = {
  create?: Prisma.XOR<Prisma.VendorCreateWithoutProductsInput, Prisma.VendorUncheckedCreateWithoutProductsInput>
  connectOrCreate?: Prisma.VendorCreateOrConnectWithoutProductsInput
  connect?: Prisma.VendorWhereUniqueInput
}

export type VendorUpdateOneRequiredWithoutProductsNestedInput = {
  create?: Prisma.XOR<Prisma.VendorCreateWithoutProductsInput, Prisma.VendorUncheckedCreateWithoutProductsInput>
  connectOrCreate?: Prisma.VendorCreateOrConnectWithoutProductsInput
  upsert?: Prisma.VendorUpsertWithoutProductsInput
  connect?: Prisma.VendorWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.VendorUpdateToOneWithWhereWithoutProductsInput, Prisma.VendorUpdateWithoutProductsInput>, Prisma.VendorUncheckedUpdateWithoutProductsInput>
}

export type VendorCreateWithoutUserInput = {
  createdAt?: Date | string
  products?: Prisma.ProductCreateNestedManyWithoutVendorInput
  store?: Prisma.StoreCreateNestedOneWithoutVendorInput
}

export type VendorUncheckedCreateWithoutUserInput = {
  id?: number
  createdAt?: Date | string
  products?: Prisma.ProductUncheckedCreateNestedManyWithoutVendorInput
  store?: Prisma.StoreUncheckedCreateNestedOneWithoutVendorInput
}

export type VendorCreateOrConnectWithoutUserInput = {
  where: Prisma.VendorWhereUniqueInput
  create: Prisma.XOR<Prisma.VendorCreateWithoutUserInput, Prisma.VendorUncheckedCreateWithoutUserInput>
}

export type VendorUpsertWithoutUserInput = {
  update: Prisma.XOR<Prisma.VendorUpdateWithoutUserInput, Prisma.VendorUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.VendorCreateWithoutUserInput, Prisma.VendorUncheckedCreateWithoutUserInput>
  where?: Prisma.VendorWhereInput
}

export type VendorUpdateToOneWithWhereWithoutUserInput = {
  where?: Prisma.VendorWhereInput
  data: Prisma.XOR<Prisma.VendorUpdateWithoutUserInput, Prisma.VendorUncheckedUpdateWithoutUserInput>
}

export type VendorUpdateWithoutUserInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  products?: Prisma.ProductUpdateManyWithoutVendorNestedInput
  store?: Prisma.StoreUpdateOneWithoutVendorNestedInput
}

export type VendorUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  products?: Prisma.ProductUncheckedUpdateManyWithoutVendorNestedInput
  store?: Prisma.StoreUncheckedUpdateOneWithoutVendorNestedInput
}

export type VendorCreateWithoutStoreInput = {
  createdAt?: Date | string
  products?: Prisma.ProductCreateNestedManyWithoutVendorInput
  user: Prisma.UserCreateNestedOneWithoutVendorInput
}

export type VendorUncheckedCreateWithoutStoreInput = {
  id?: number
  createdAt?: Date | string
  userId: number
  products?: Prisma.ProductUncheckedCreateNestedManyWithoutVendorInput
}

export type VendorCreateOrConnectWithoutStoreInput = {
  where: Prisma.VendorWhereUniqueInput
  create: Prisma.XOR<Prisma.VendorCreateWithoutStoreInput, Prisma.VendorUncheckedCreateWithoutStoreInput>
}

export type VendorUpsertWithoutStoreInput = {
  update: Prisma.XOR<Prisma.VendorUpdateWithoutStoreInput, Prisma.VendorUncheckedUpdateWithoutStoreInput>
  create: Prisma.XOR<Prisma.VendorCreateWithoutStoreInput, Prisma.VendorUncheckedCreateWithoutStoreInput>
  where?: Prisma.VendorWhereInput
}

export type VendorUpdateToOneWithWhereWithoutStoreInput = {
  where?: Prisma.VendorWhereInput
  data: Prisma.XOR<Prisma.VendorUpdateWithoutStoreInput, Prisma.VendorUncheckedUpdateWithoutStoreInput>
}

export type VendorUpdateWithoutStoreInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  products?: Prisma.ProductUpdateManyWithoutVendorNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutVendorNestedInput
}

export type VendorUncheckedUpdateWithoutStoreInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  products?: Prisma.ProductUncheckedUpdateManyWithoutVendorNestedInput
}

export type VendorCreateWithoutProductsInput = {
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutVendorInput
  store?: Prisma.StoreCreateNestedOneWithoutVendorInput
}

export type VendorUncheckedCreateWithoutProductsInput = {
  id?: number
  createdAt?: Date | string
  userId: number
  store?: Prisma.StoreUncheckedCreateNestedOneWithoutVendorInput
}

export type VendorCreateOrConnectWithoutProductsInput = {
  where: Prisma.VendorWhereUniqueInput
  create: Prisma.XOR<Prisma.VendorCreateWithoutProductsInput, Prisma.VendorUncheckedCreateWithoutProductsInput>
}

export type VendorUpsertWithoutProductsInput = {
  update: Prisma.XOR<Prisma.VendorUpdateWithoutProductsInput, Prisma.VendorUncheckedUpdateWithoutProductsInput>
  create: Prisma.XOR<Prisma.VendorCreateWithoutProductsInput, Prisma.VendorUncheckedCreateWithoutProductsInput>
  where?: Prisma.VendorWhereInput
}

export type VendorUpdateToOneWithWhereWithoutProductsInput = {
  where?: Prisma.VendorWhereInput
  data: Prisma.XOR<Prisma.VendorUpdateWithoutProductsInput, Prisma.VendorUncheckedUpdateWithoutProductsInput>
}

export type VendorUpdateWithoutProductsInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutVendorNestedInput
  store?: Prisma.StoreUpdateOneWithoutVendorNestedInput
}

export type VendorUncheckedUpdateWithoutProductsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  store?: Prisma.StoreUncheckedUpdateOneWithoutVendorNestedInput
}


/**
 * Count Type VendorCountOutputType
 */

export type VendorCountOutputType = {
  products: number
}

export type VendorCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  products?: boolean | VendorCountOutputTypeCountProductsArgs
}

/**
 * VendorCountOutputType without action
 */
export type VendorCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VendorCountOutputType
   */
  select?: Prisma.VendorCountOutputTypeSelect<ExtArgs> | null
}

/**
 * VendorCountOutputType without action
 */
export type VendorCountOutputTypeCountProductsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProductWhereInput
}


export type VendorSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  userId?: boolean
  products?: boolean | Prisma.Vendor$productsArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  store?: boolean | Prisma.Vendor$storeArgs<ExtArgs>
  _count?: boolean | Prisma.VendorCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["vendor"]>

export type VendorSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  userId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["vendor"]>

export type VendorSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  userId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["vendor"]>

export type VendorSelectScalar = {
  id?: boolean
  createdAt?: boolean
  userId?: boolean
}

export type VendorOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "userId", ExtArgs["result"]["vendor"]>
export type VendorInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  products?: boolean | Prisma.Vendor$productsArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  store?: boolean | Prisma.Vendor$storeArgs<ExtArgs>
  _count?: boolean | Prisma.VendorCountOutputTypeDefaultArgs<ExtArgs>
}
export type VendorIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type VendorIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $VendorPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Vendor"
  objects: {
    products: Prisma.$ProductPayload<ExtArgs>[]
    user: Prisma.$UserPayload<ExtArgs>
    store: Prisma.$StorePayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    createdAt: Date
    userId: number
  }, ExtArgs["result"]["vendor"]>
  composites: {}
}

export type VendorGetPayload<S extends boolean | null | undefined | VendorDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$VendorPayload, S>

export type VendorCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<VendorFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: VendorCountAggregateInputType | true
  }

export interface VendorDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Vendor'], meta: { name: 'Vendor' } }
  /**
   * Find zero or one Vendor that matches the filter.
   * @param {VendorFindUniqueArgs} args - Arguments to find a Vendor
   * @example
   * // Get one Vendor
   * const vendor = await prisma.vendor.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends VendorFindUniqueArgs>(args: Prisma.SelectSubset<T, VendorFindUniqueArgs<ExtArgs>>): Prisma.Prisma__VendorClient<runtime.Types.Result.GetResult<Prisma.$VendorPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Vendor that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {VendorFindUniqueOrThrowArgs} args - Arguments to find a Vendor
   * @example
   * // Get one Vendor
   * const vendor = await prisma.vendor.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends VendorFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, VendorFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__VendorClient<runtime.Types.Result.GetResult<Prisma.$VendorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Vendor that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VendorFindFirstArgs} args - Arguments to find a Vendor
   * @example
   * // Get one Vendor
   * const vendor = await prisma.vendor.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends VendorFindFirstArgs>(args?: Prisma.SelectSubset<T, VendorFindFirstArgs<ExtArgs>>): Prisma.Prisma__VendorClient<runtime.Types.Result.GetResult<Prisma.$VendorPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Vendor that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VendorFindFirstOrThrowArgs} args - Arguments to find a Vendor
   * @example
   * // Get one Vendor
   * const vendor = await prisma.vendor.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends VendorFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, VendorFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__VendorClient<runtime.Types.Result.GetResult<Prisma.$VendorPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Vendors that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VendorFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Vendors
   * const vendors = await prisma.vendor.findMany()
   * 
   * // Get first 10 Vendors
   * const vendors = await prisma.vendor.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const vendorWithIdOnly = await prisma.vendor.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends VendorFindManyArgs>(args?: Prisma.SelectSubset<T, VendorFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VendorPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Vendor.
   * @param {VendorCreateArgs} args - Arguments to create a Vendor.
   * @example
   * // Create one Vendor
   * const Vendor = await prisma.vendor.create({
   *   data: {
   *     // ... data to create a Vendor
   *   }
   * })
   * 
   */
  create<T extends VendorCreateArgs>(args: Prisma.SelectSubset<T, VendorCreateArgs<ExtArgs>>): Prisma.Prisma__VendorClient<runtime.Types.Result.GetResult<Prisma.$VendorPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Vendors.
   * @param {VendorCreateManyArgs} args - Arguments to create many Vendors.
   * @example
   * // Create many Vendors
   * const vendor = await prisma.vendor.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends VendorCreateManyArgs>(args?: Prisma.SelectSubset<T, VendorCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Vendors and returns the data saved in the database.
   * @param {VendorCreateManyAndReturnArgs} args - Arguments to create many Vendors.
   * @example
   * // Create many Vendors
   * const vendor = await prisma.vendor.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Vendors and only return the `id`
   * const vendorWithIdOnly = await prisma.vendor.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends VendorCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, VendorCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VendorPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Vendor.
   * @param {VendorDeleteArgs} args - Arguments to delete one Vendor.
   * @example
   * // Delete one Vendor
   * const Vendor = await prisma.vendor.delete({
   *   where: {
   *     // ... filter to delete one Vendor
   *   }
   * })
   * 
   */
  delete<T extends VendorDeleteArgs>(args: Prisma.SelectSubset<T, VendorDeleteArgs<ExtArgs>>): Prisma.Prisma__VendorClient<runtime.Types.Result.GetResult<Prisma.$VendorPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Vendor.
   * @param {VendorUpdateArgs} args - Arguments to update one Vendor.
   * @example
   * // Update one Vendor
   * const vendor = await prisma.vendor.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends VendorUpdateArgs>(args: Prisma.SelectSubset<T, VendorUpdateArgs<ExtArgs>>): Prisma.Prisma__VendorClient<runtime.Types.Result.GetResult<Prisma.$VendorPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Vendors.
   * @param {VendorDeleteManyArgs} args - Arguments to filter Vendors to delete.
   * @example
   * // Delete a few Vendors
   * const { count } = await prisma.vendor.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends VendorDeleteManyArgs>(args?: Prisma.SelectSubset<T, VendorDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Vendors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VendorUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Vendors
   * const vendor = await prisma.vendor.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends VendorUpdateManyArgs>(args: Prisma.SelectSubset<T, VendorUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Vendors and returns the data updated in the database.
   * @param {VendorUpdateManyAndReturnArgs} args - Arguments to update many Vendors.
   * @example
   * // Update many Vendors
   * const vendor = await prisma.vendor.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Vendors and only return the `id`
   * const vendorWithIdOnly = await prisma.vendor.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends VendorUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, VendorUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VendorPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Vendor.
   * @param {VendorUpsertArgs} args - Arguments to update or create a Vendor.
   * @example
   * // Update or create a Vendor
   * const vendor = await prisma.vendor.upsert({
   *   create: {
   *     // ... data to create a Vendor
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Vendor we want to update
   *   }
   * })
   */
  upsert<T extends VendorUpsertArgs>(args: Prisma.SelectSubset<T, VendorUpsertArgs<ExtArgs>>): Prisma.Prisma__VendorClient<runtime.Types.Result.GetResult<Prisma.$VendorPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Vendors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VendorCountArgs} args - Arguments to filter Vendors to count.
   * @example
   * // Count the number of Vendors
   * const count = await prisma.vendor.count({
   *   where: {
   *     // ... the filter for the Vendors we want to count
   *   }
   * })
  **/
  count<T extends VendorCountArgs>(
    args?: Prisma.Subset<T, VendorCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], VendorCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Vendor.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VendorAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends VendorAggregateArgs>(args: Prisma.Subset<T, VendorAggregateArgs>): Prisma.PrismaPromise<GetVendorAggregateType<T>>

  /**
   * Group by Vendor.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VendorGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends VendorGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: VendorGroupByArgs['orderBy'] }
      : { orderBy?: VendorGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, VendorGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetVendorGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Vendor model
 */
readonly fields: VendorFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Vendor.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__VendorClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  products<T extends Prisma.Vendor$productsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Vendor$productsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  store<T extends Prisma.Vendor$storeArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Vendor$storeArgs<ExtArgs>>): Prisma.Prisma__StoreClient<runtime.Types.Result.GetResult<Prisma.$StorePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Vendor model
 */
export interface VendorFieldRefs {
  readonly id: Prisma.FieldRef<"Vendor", 'Int'>
  readonly createdAt: Prisma.FieldRef<"Vendor", 'DateTime'>
  readonly userId: Prisma.FieldRef<"Vendor", 'Int'>
}
    

// Custom InputTypes
/**
 * Vendor findUnique
 */
export type VendorFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vendor
   */
  select?: Prisma.VendorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Vendor
   */
  omit?: Prisma.VendorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VendorInclude<ExtArgs> | null
  /**
   * Filter, which Vendor to fetch.
   */
  where: Prisma.VendorWhereUniqueInput
}

/**
 * Vendor findUniqueOrThrow
 */
export type VendorFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vendor
   */
  select?: Prisma.VendorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Vendor
   */
  omit?: Prisma.VendorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VendorInclude<ExtArgs> | null
  /**
   * Filter, which Vendor to fetch.
   */
  where: Prisma.VendorWhereUniqueInput
}

/**
 * Vendor findFirst
 */
export type VendorFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vendor
   */
  select?: Prisma.VendorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Vendor
   */
  omit?: Prisma.VendorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VendorInclude<ExtArgs> | null
  /**
   * Filter, which Vendor to fetch.
   */
  where?: Prisma.VendorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Vendors to fetch.
   */
  orderBy?: Prisma.VendorOrderByWithRelationInput | Prisma.VendorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Vendors.
   */
  cursor?: Prisma.VendorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Vendors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Vendors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Vendors.
   */
  distinct?: Prisma.VendorScalarFieldEnum | Prisma.VendorScalarFieldEnum[]
}

/**
 * Vendor findFirstOrThrow
 */
export type VendorFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vendor
   */
  select?: Prisma.VendorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Vendor
   */
  omit?: Prisma.VendorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VendorInclude<ExtArgs> | null
  /**
   * Filter, which Vendor to fetch.
   */
  where?: Prisma.VendorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Vendors to fetch.
   */
  orderBy?: Prisma.VendorOrderByWithRelationInput | Prisma.VendorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Vendors.
   */
  cursor?: Prisma.VendorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Vendors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Vendors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Vendors.
   */
  distinct?: Prisma.VendorScalarFieldEnum | Prisma.VendorScalarFieldEnum[]
}

/**
 * Vendor findMany
 */
export type VendorFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vendor
   */
  select?: Prisma.VendorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Vendor
   */
  omit?: Prisma.VendorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VendorInclude<ExtArgs> | null
  /**
   * Filter, which Vendors to fetch.
   */
  where?: Prisma.VendorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Vendors to fetch.
   */
  orderBy?: Prisma.VendorOrderByWithRelationInput | Prisma.VendorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Vendors.
   */
  cursor?: Prisma.VendorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Vendors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Vendors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Vendors.
   */
  distinct?: Prisma.VendorScalarFieldEnum | Prisma.VendorScalarFieldEnum[]
}

/**
 * Vendor create
 */
export type VendorCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vendor
   */
  select?: Prisma.VendorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Vendor
   */
  omit?: Prisma.VendorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VendorInclude<ExtArgs> | null
  /**
   * The data needed to create a Vendor.
   */
  data: Prisma.XOR<Prisma.VendorCreateInput, Prisma.VendorUncheckedCreateInput>
}

/**
 * Vendor createMany
 */
export type VendorCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Vendors.
   */
  data: Prisma.VendorCreateManyInput | Prisma.VendorCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Vendor createManyAndReturn
 */
export type VendorCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vendor
   */
  select?: Prisma.VendorSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Vendor
   */
  omit?: Prisma.VendorOmit<ExtArgs> | null
  /**
   * The data used to create many Vendors.
   */
  data: Prisma.VendorCreateManyInput | Prisma.VendorCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VendorIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Vendor update
 */
export type VendorUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vendor
   */
  select?: Prisma.VendorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Vendor
   */
  omit?: Prisma.VendorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VendorInclude<ExtArgs> | null
  /**
   * The data needed to update a Vendor.
   */
  data: Prisma.XOR<Prisma.VendorUpdateInput, Prisma.VendorUncheckedUpdateInput>
  /**
   * Choose, which Vendor to update.
   */
  where: Prisma.VendorWhereUniqueInput
}

/**
 * Vendor updateMany
 */
export type VendorUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Vendors.
   */
  data: Prisma.XOR<Prisma.VendorUpdateManyMutationInput, Prisma.VendorUncheckedUpdateManyInput>
  /**
   * Filter which Vendors to update
   */
  where?: Prisma.VendorWhereInput
  /**
   * Limit how many Vendors to update.
   */
  limit?: number
}

/**
 * Vendor updateManyAndReturn
 */
export type VendorUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vendor
   */
  select?: Prisma.VendorSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Vendor
   */
  omit?: Prisma.VendorOmit<ExtArgs> | null
  /**
   * The data used to update Vendors.
   */
  data: Prisma.XOR<Prisma.VendorUpdateManyMutationInput, Prisma.VendorUncheckedUpdateManyInput>
  /**
   * Filter which Vendors to update
   */
  where?: Prisma.VendorWhereInput
  /**
   * Limit how many Vendors to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VendorIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Vendor upsert
 */
export type VendorUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vendor
   */
  select?: Prisma.VendorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Vendor
   */
  omit?: Prisma.VendorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VendorInclude<ExtArgs> | null
  /**
   * The filter to search for the Vendor to update in case it exists.
   */
  where: Prisma.VendorWhereUniqueInput
  /**
   * In case the Vendor found by the `where` argument doesn't exist, create a new Vendor with this data.
   */
  create: Prisma.XOR<Prisma.VendorCreateInput, Prisma.VendorUncheckedCreateInput>
  /**
   * In case the Vendor was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.VendorUpdateInput, Prisma.VendorUncheckedUpdateInput>
}

/**
 * Vendor delete
 */
export type VendorDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vendor
   */
  select?: Prisma.VendorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Vendor
   */
  omit?: Prisma.VendorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VendorInclude<ExtArgs> | null
  /**
   * Filter which Vendor to delete.
   */
  where: Prisma.VendorWhereUniqueInput
}

/**
 * Vendor deleteMany
 */
export type VendorDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Vendors to delete
   */
  where?: Prisma.VendorWhereInput
  /**
   * Limit how many Vendors to delete.
   */
  limit?: number
}

/**
 * Vendor.products
 */
export type Vendor$productsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Product
   */
  select?: Prisma.ProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Product
   */
  omit?: Prisma.ProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductInclude<ExtArgs> | null
  where?: Prisma.ProductWhereInput
  orderBy?: Prisma.ProductOrderByWithRelationInput | Prisma.ProductOrderByWithRelationInput[]
  cursor?: Prisma.ProductWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProductScalarFieldEnum | Prisma.ProductScalarFieldEnum[]
}

/**
 * Vendor.store
 */
export type Vendor$storeArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Store
   */
  select?: Prisma.StoreSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Store
   */
  omit?: Prisma.StoreOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreInclude<ExtArgs> | null
  where?: Prisma.StoreWhereInput
}

/**
 * Vendor without action
 */
export type VendorDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vendor
   */
  select?: Prisma.VendorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Vendor
   */
  omit?: Prisma.VendorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VendorInclude<ExtArgs> | null
}
